# Packager configuration for Spotlight Dimmer
# Documentation: https://docs.crabnebula.dev/packager/configuration/

# Product Information
product_name = "Spotlight Dimmer"
version = "0.5.9"
identifier = "com.thomazmoura.spotlight-dimmer"
publisher = "Thomaz Moura"
authors = ["Thomaz Moura"]
homepage = "https://github.com/thomazmoura/spotlight-dimmer"
license_file = "LICENSE"

# Short description for package managers
description = "A lightweight Windows application that dims inactive displays to highlight the active one."

# Long description for installers
long_description = """
Spotlight Dimmer helps you focus by dimming all displays except the one with your currently active window.

Features:
• Ultra-lightweight: Only ~7.6 MB RAM usage
• Real-time Monitoring: Instantly detects window focus changes
• Click-through Overlays: Dimming doesn't interfere with your workflow
• Native Windows API: No browser engine overhead, instant startup
• Auto-reload Config: Changes detected instantly via file system notifications

Perfect for multi-monitor setups!
"""

# Build configuration
# before_packaging_command = "cargo build --release --bin spotlight-dimmer --bin spotlight-dimmer-config"

# Binaries to package
binaries = [
    { path = "target/release/spotlight-dimmer.exe", main = true },
    { path = "target/release/spotlight-dimmer-config.exe", main = false }
]

# Resources to include in installation
resources = [
    "spotlight-dimmer-icon.ico",
    "spotlight-dimmer-icon-paused.ico",
    "README.md",
    "LICENSE"
]

# Application icon (for installer and Start Menu)
icons = ["src/icons/icon.ico"]

# Windows-specific configuration
[windows]
# Allow downgrades for beta versioning
allow_downgrades = true

# NSIS Installer Configuration
[nsis]
# Install mode: "currentUser" = No admin required, per-user installation
# "perMachine" = Requires admin, system-wide installation
# "both" = User can choose
install-mode = "currentUser"

# Compression algorithm (lzma provides best compression)
compression = "lzma"

# Installer languages
languages = ["English"]

# Display language selector before installation
display-language-selector = false

# Installer header image (optional - 150x57px recommended)
# headerImage = "installer-header.bmp"

# Installer sidebar image (optional - 164x314px recommended)
# sidebarImage = "installer-sidebar.bmp"

# Installer icon (sets the icon for the installer .exe itself and MUI_ICON for the wizard)
installer-icon = "src/icons/icon.ico"

# Custom NSIS template with explicit icon parameters for shortcuts
template = "custom-installer-template.nsi"

# Uninstaller configuration
# Automatically handled - creates uninstaller in installation directory
# Adds "Add/Remove Programs" entry for proper Windows integration
