name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-pc-windows-gnu

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run tests
        run: cargo test --lib --verbose --target x86_64-pc-windows-gnu

      - name: Run doc tests
        run: cargo test --doc --verbose
        continue-on-error: true  # Doc tests might not exist yet

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: x86_64-pc-windows-gnu

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --target x86_64-pc-windows-gnu -- -W clippy::all -A dead_code

  fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Build binaries
        run: cargo build --release --target x86_64-pc-windows-gnu --bin spotlight-dimmer --bin spotlight-dimmer-config

      - name: Check binary sizes
        run: |
          mainSize=$(stat -c%s target/x86_64-pc-windows-gnu/release/spotlight-dimmer.exe)
          configSize=$(stat -c%s target/x86_64-pc-windows-gnu/release/spotlight-dimmer-config.exe)
          echo "spotlight-dimmer.exe: $(echo "scale=2; $mainSize/1024" | bc) KB"
          echo "spotlight-dimmer-config.exe: $(echo "scale=2; $configSize/1024" | bc) KB"
